import { supabase } from '../utils/supabaseClient';

export enum TransactionAction {
  BUY = 'BUY',
  SELL = 'SELL',
}

export interface ReconcileRow {
  id?: number;              // optional primary key if you define one in Supabase
  user_id?: string;         // supabase auth user id; requires a column in the table
  game: string;
  action: TransactionAction;  // 'BUY' or 'SELL'
  amount: number;
  image: string;
  date?: string;            // transaction date (ISO 8601 format)
  created_at?: string;      // autogenerated by Supabase if you have a timestamptz
}

/**
 * Insert a new transaction into the `reconcile` table.
 *
 * The `created_at` column is automatically populated by the database,
 * so callers should omit it.
 */
export async function insertTransaction(
  tx: Omit<ReconcileRow, 'created_at' | 'id'>
): Promise<ReconcileRow> {
  const { data, error } = await supabase
    .from('reconcile')
    .insert(tx)
    .select()
    .single();

  if (error) {
    throw error;
  }

  return data as ReconcileRow;
}

/**
 * Fetch all records from the `reconcile` table, ordered by creation date.
 */
export async function fetchTransactions(userId?: string): Promise<ReconcileRow[]> {
  let query = supabase
    .from('reconcile')
    .select('*')
    .order('created_at', { ascending: true });

  if (userId) {
    query = query.eq('user_id', userId);
  }

  const { data, error } = await query;

  if (error) {
    throw error;
  }

  return data || [];
}

/**
 * Delete a transaction from the `reconcile` table by ID.
 */
export async function deleteTransaction(id: number, userId?: string): Promise<void> {
  let query = supabase
    .from('reconcile')
    .delete()
    .eq('id', id);

  if (userId) {
    query = query.eq('user_id', userId);
  }

  const { error } = await query;

  if (error) {
    throw error;
  }
}

